# Generated by nixos-generate-config — do not edit manually.
# To regenerate: sudo nixos-generate-config --show-hardware-config
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules          = [ ];
  boot.kernelModules                 = [ "kvm-intel" ];
  boot.extraModulePackages           = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7c6d7c6f-2c36-4208-822d-e2d2f3e341ec";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device  = "/dev/disk/by-uuid/9563-05F1";
    fsType  = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0cb15c09-f7d2-4670-9d72-2b167c0c11a8";
    fsType = "ext4";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform           = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
