{ pkgs, lib, inputs, ... }:

{
  imports = [
    ./hyprland
  ];

  home.username      = "spectre";
  home.homeDirectory = "/home/spectre";
  home.stateVersion  = "25.11";

  programs.home-manager.enable = true;

  # ── Packages ──────────────────────────────────────────────────────────────
  home.packages = with pkgs; [
    # Browsers & editors
    brave
    vscode

    # CLI tools
    git
    curl
    wget
    bc
    ffmpeg
    fastfetch
    eza

    # File managers
    nautilus

    # Media
    playerctl

    # Theming — Material You pipeline
    matugen      # Generate Material You palette from wallpaper
    pywal16      # Classic pywal color generation
    papirus-icon-theme
    bibata-cursors
    adw-gtk3
  ];

  # ── GTK theming ──────────────────────────────────────────────────────────
  gtk = {
    enable = true;
    iconTheme = {
      name    = "Papirus-Dark";
      package = pkgs.papirus-icon-theme;
    };
    # CSS is managed dynamically by Ambxst, so we skip extraCss here
  };

  # ── dconf: GNOME dark preference + icon theme ──────────────────────────
  dconf.settings = {
    "org/gnome/desktop/interface" = {
      color-scheme = "prefer-dark";
      icon-theme   = "Papirus-Dark";
      gtk-theme    = "adw-gtk3-dark";
    };
  };

  # ── Cursor theme (consistent across GTK + Hyprland) ────────────────────
  home.pointerCursor = {
    name    = "Adwaita";
    package = pkgs.adwaita-icon-theme;
    size    = 24;
    gtk.enable = true;
  };

  # ── XDG ───────────────────────────────────────────────────────────────────
  xdg.enable = true;
  xdg.configFile."matugen/config.toml".source = ./matugen/config.toml;
  xdg.configFile."fastfetch/config.jsonc".source = ./fastfetch.jsonc;

  # ── Starship prompt ────────────────────────────────────────────────────────
  programs.starship = {
    enable = true;
    enableFishIntegration = true;
    enableBashIntegration = false;
    settings = builtins.fromTOML (builtins.readFile ./starship.toml);
  };

  # ── Shell: fish (primary) ─────────────────────────────────────────────────
  programs.fish = {
    enable = true;
    interactiveShellInit = ''
      set -g fish_greeting
      # Clear screen and show system info
      fastfetch
      # Use I-beam cursor in insert mode
      set -g fish_cursor_default block
      set -g fish_cursor_insert line
      set -g fish_cursor_replace_one underscore
      set -g fish_cursor_visual block

      # Dynamic syntax highlighting (responds to wallpaper)
      set -g fish_color_command green --bold
      set -g fish_color_param cyan
      set -g fish_color_keyword pink
      set -g fish_color_quote yellow
      set -g fish_color_redirection purple
      set -g fish_color_end green
      set -g fish_color_error red
      set -g fish_color_comment brblack
      set -g fish_color_selection --background=brblack
      set -g fish_color_operator green
      set -g fish_color_escape pink
      set -g fish_color_autosuggestion brblack
    '';
    shellAliases = {
      ls     = "eza --icons";
      ll     = "eza -lah --icons";
      ".."   = "cd ..";
      # Rebuild shortcuts
      nrs    = "sudo nixos-rebuild switch --flake ~/nixos#skynet";
      hms    = "home-manager switch --flake ~/nixos#spectre@skynet";
      update = "sudo nixos-rebuild switch --flake ~/nixos#skynet";
      # Manual cleanup for wallpaper leaks
      clean-leaks = "pgrep -u $USER mpvpaper | sort -n | head -n -1 | xargs kill -9 2>/dev/null";
    };
  };

  # ── Shell: bash (fallback) ────────────────────────────────────────────────
  programs.bash = {
    enable       = true;
    initExtra = ''
      # Force aliases to ensure they override system defaults
      alias ls='eza --icons'
      alias ll='eza -lah --icons'
      alias ..='cd ..'
      alias nrs='sudo nixos-rebuild switch --flake ~/nixos#skynet'
      alias hms='home-manager switch --flake ~/nixos#spectre@skynet'
      # Manual cleanup for wallpaper leaks
      alias clean-leaks="pgrep -u $USER mpvpaper | sort -n | head -n -1 | xargs kill -9 2>/dev/null"
    '';
  };

  # ── Terminal ──────────────────────────────────────────────────────────────
  programs.kitty = {
    enable   = true;
    extraConfig = ''
      # Include dynamic colors generated by ambxst/pywal wrapper
      include ~/.cache/wal/colors-kitty.conf
    '';
    settings = {
      shell                   = "${pkgs.fish}/bin/fish";
      cursor_shape            = "beam";
      default_pointer_shape   = "arrow";
      confirm_os_window_close = 0;
      enable_audio_bell       = false;
      window_padding_width    = "0 10 10 10";
    };
  };

  # ── Auto-update Kitty theme on Ambxst theme change ────────────────────────
  systemd.user.services.kitty-theme-watcher = {
    Unit = {
      Description = "Update Kitty colors when Ambxst theme changes";
      After = [ "graphical-session.target" ];
    };
    Install.WantedBy = [ "graphical-session.target" ];
    Service = {
      ExecStart = "${pkgs.writeShellScript "kitty-colors-watcher" ''
        generate() {
          if [ -f ~/.cache/wal/colors.json ]; then
            ${pkgs.jq}/bin/jq -r ' "background " + .special.background, "foreground " + .special.foreground, "cursor " + .special.cursor, "selection_background " + .colors.color8, "selection_foreground " + .special.foreground, "color0 " + .colors.color0, "color1 " + .colors.color1, "color2 " + .colors.color2, "color3 " + .colors.color3, "color4 " + .colors.color4, "color5 " + .colors.color5, "color6 " + .colors.color6, "color7 " + .colors.color7, "color8 " + .colors.color8, "color9 " + .colors.color9, "color10 " + .colors.color10, "color11 " + .colors.color11, "color12 " + .colors.color12, "color13 " + .colors.color13, "color14 " + .colors.color14, "color15 " + .colors.color15 ' ~/.cache/wal/colors.json > ~/.cache/wal/colors-kitty.conf
          fi
        }
        
        generate
        
        while ${pkgs.inotify-tools}/bin/inotifywait -e modify,close_write ~/.cache/wal/colors.json; do
          # Small delay to ensure ambxst/pywal has finished writing
          sleep 0.2
          generate
          # Tell all kitty instances to reload config
          ${pkgs.procps}/bin/pkill -USR1 -x kitty || true
        done
      ''}";
      Restart = "always";
      RestartSec = "2";
    };
  };

  # ── Ensure ambxst configs are writable ────────────────────────────────────
  home.activation = {
    makeAmbxstConfigWritable = lib.hm.dag.entryAfter ["writeBoundary"] ''
      for dir in "$HOME/.config/ambxst" "$HOME/.local/share/ambxst" "$HOME/.local/state/ambxst" "$HOME/.cache/ambxst"; do
        if [ -d "$dir" ]; then
          $DRY_RUN_CMD chmod -R u+w "$dir"
        fi
      done
    '';
  };

}
