{ pkgs, inputs, ... }:

{
  imports = [
    ./hyprland
  ];

  home.username      = "spectre";
  home.homeDirectory = "/home/spectre";
  home.stateVersion  = "25.11";

  programs.home-manager.enable = true;

  # ── Packages ──────────────────────────────────────────────────────────────
  home.packages = with pkgs; [
    # Browsers & editors
    brave
    vscode

    # CLI tools
    git
    curl
    wget
    bc
    ffmpeg
    fastfetch
    eza

    # File managers
    nautilus

    # Media
    playerctl

    # Theming — Material You pipeline
    matugen      # Generate Material You palette from wallpaper
    pywal16      # Classic pywal color generation
    papirus-icon-theme
    bibata-cursors
    adw-gtk3
  ];

  # ── GTK theming ──────────────────────────────────────────────────────────
  gtk = {
    enable = true;
    iconTheme = {
      name    = "Papirus-Dark";
      package = pkgs.papirus-icon-theme;
    };
    # CSS is managed dynamically by Ambxst, so we skip extraCss here
  };

  # ── dconf: GNOME dark preference + icon theme ──────────────────────────
  dconf.settings = {
    "org/gnome/desktop/interface" = {
      color-scheme = "prefer-dark";
      icon-theme   = "Papirus-Dark";
      gtk-theme    = "adw-gtk3-dark";
    };
  };

  # ── Cursor theme (consistent across GTK + Hyprland) ────────────────────
  home.pointerCursor = {
    name    = "Bibata-Modern-Classic";
    package = pkgs.bibata-cursors;
    size    = 24;
    gtk.enable = true;
  };

  # ── XDG ───────────────────────────────────────────────────────────────────
  xdg.enable = true;

  # ── Starship prompt ────────────────────────────────────────────────────────
  programs.starship = {
    enable = true;
    enableFishIntegration = true;
    enableBashIntegration = false;
    settings = builtins.fromTOML (builtins.readFile ./starship.toml);
  };

  # ── Shell: fish (primary) ─────────────────────────────────────────────────
  programs.fish = {
    enable = true;
    interactiveShellInit = "set -g fish_greeting";
    shellAliases = {
      ls     = "eza --icons";
      ll     = "eza -lah --icons";
      ".."   = "cd ..";
      # Rebuild shortcuts
      nrs    = "sudo nixos-rebuild switch --flake ~/nixos#skynet";
      hms    = "home-manager switch --flake ~/nixos#spectre@skynet";
      update = "sudo nixos-rebuild switch --flake ~/nixos#skynet";
    };
  };

  # ── Shell: bash (fallback) ────────────────────────────────────────────────
  programs.bash = {
    enable       = true;
    shellAliases = {
      ls  = "eza --icons";
      ll  = "eza -lah --icons";
      ".." = "cd ..";
      nrs = "sudo nixos-rebuild switch --flake ~/nixos#skynet";
      hms = "home-manager switch --flake ~/nixos#spectre@skynet";
    };
  };

  # ── Terminal ──────────────────────────────────────────────────────────────
  programs.kitty = {
    enable   = true;
    extraConfig = ''
      # Include dynamic colors generated by ambxst/pywal wrapper
      include ~/.cache/wal/colors-kitty.conf
    '';
    settings = {
      shell                   = "fish";
      confirm_os_window_close = 0;
      enable_audio_bell       = false;
      window_padding_width    = 10;
    };
  };

  # ── Auto-update Kitty theme on Ambxst theme change ────────────────────────
  systemd.user.services.kitty-theme-watcher = {
    Unit = {
      Description = "Update Kitty colors when Ambxst theme changes";
      After = [ "graphical-session.target" ];
    };
    Install.WantedBy = [ "graphical-session.target" ];
    Service = {
      ExecStart = "${pkgs.writeShellScript "kitty-colors-watcher" ''
        generate() {
          if [ -f ~/.cache/wal/colors.json ]; then
            ${pkgs.jq}/bin/jq -r ' "background " + .special.background, "foreground " + .special.foreground, "cursor " + .special.cursor, "selection_background " + .colors.color8, "selection_foreground " + .special.foreground, "color0 " + .colors.color0, "color1 " + .colors.color1, "color2 " + .colors.color2, "color3 " + .colors.color3, "color4 " + .colors.color4, "color5 " + .colors.color5, "color6 " + .colors.color6, "color7 " + .colors.color7, "color8 " + .colors.color8, "color9 " + .colors.color9, "color10 " + .colors.color10, "color11 " + .colors.color11, "color12 " + .colors.color12, "color13 " + .colors.color13, "color14 " + .colors.color14, "color15 " + .colors.color15 ' ~/.cache/wal/colors.json > ~/.cache/wal/colors-kitty.conf
          fi
        }
        
        generate
        
        while ${pkgs.inotify-tools}/bin/inotifywait -e modify,close_write ~/.cache/wal/colors.json; do
          generate
          # Tell all kitty instances to reload config
          ${pkgs.procps}/bin/pkill -USR1 -x kitty || true
        done
      ''}";
      Restart = "always";
      RestartSec = "2";
    };
  };

  # ── Ensure ambxst configs are writable ────────────────────────────────────
  home.activation = {
    makeAmbxstConfigWritable = pkgs.lib.hm.dag.entryAfter ["writeBoundary"] ''
      if [ -d $HOME/.config/ambxst/config ]; then
        $DRY_RUN_CMD chmod -R u+w $HOME/.config/ambxst/config
      fi
    '';
  };
}
